services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
